# Generated by Django 5.2.14 on 2026-06-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_submission_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('fair', 'Fair'), ('excellent', 'Excellent')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
