# Generated by Django 5.2.14 on 2026-06-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submission_grade_submission_marks_submission_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='student_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
